- Makefile
Make file bug fixed. Braces added
> Minor bug fix

- iter8_analytics/api/analytics/endpoints/analytics.py
- iter8_analytics/api/analytics/iter8experiment.py
- iter8_analytics/api/analytics/iter8response.py
- iter8_analytics/api/analytics/request_parameters.py
- iter8_analytics/api/analytics/responses.py
- tests/api/analytics/endpoints/analytics_tests.py
- Modified required parameters for PBR
- Created a Rest End Point for PBR
- Added a simple test case
- Added code stubs in the algorithm- none of the methods are called as of now
> Request parameters and class stubs for pbr

- install/knative/iter8-analytics.yaml
prereq for https://github.com/iter8-tools/docs/pull/13
> install iter8-analytics for knative

- iter8_analytics/api/analytics/iter8response.py
- Updated pseudo code for PBR
- Created class stubs
> Created class stubs for pbr

- iter8_analytics/api/analytics/iter8experiment.py
- iter8_analytics/api/analytics/iter8response.py
- iter8_analytics/api/analytics/request_parameters.py
- iter8_analytics/api/analytics/responses.py
- iter8_analytics/api/analytics/successcriteria.py
- iter8_analytics/metrics_backend/iter8metric.py
- iter8_analytics/metrics_backend/prometheusquery.py
- tests/api/analytics/endpoints/analytics_tests.py
- tests/metrics_backend/prometheusquery_tests.py
- tests/metrics_backend/successcriteria_tests.py
- Replaced Metric Type and Metric Nature to is_counter and absent_value keys
- Resolving #24
> Metric type change

- iter8_analytics/api/analytics/iter8experiment.py
- iter8_analytics/api/analytics/request_parameters.py
- tests/api/analytics/endpoints/analytics_tests.py
> Last state added to PBR/OBR

- iter8_analytics/api/analytics/iter8experiment.py
- iter8_analytics/api/analytics/iter8response.py
- iter8_analytics/api/analytics/responses.py
- tests/api/analytics/endpoints/analytics_tests.py
> Added belief details to last state for PBR/OBR

- grep
- iter8_analytics/api/analytics/endpoints/analytics.py
- iter8_analytics/api/analytics/iter8experiment.py
- iter8_analytics/api/analytics/iter8response.py
- iter8_analytics/api/analytics/request_parameters.py
- tests/api/analytics/endpoints/analytics_tests.py
Modified code to use last state information when None is returned by prometheus object
Resolves #31
> Fixed Z value bug

- iter8_analytics/api/analytics/iter8experiment.py
- tests/api/analytics/endpoints/analytics_tests.py
- tests/metrics_backend/successcriteria_tests.py
> Added reward and metric criterion base class

- iter8_analytics/api/analytics/endpoints/analytics.py
- tests/api/analytics/endpoints/analytics_tests.py
> Algorithms endpoint

- iter8_analytics/api/analytics/iter8experiment.py
- iter8_analytics/api/analytics/iter8response.py
- tests/api/analytics/endpoints/analytics_tests.py
> Fixed python error bug

- tests/e2e/build-image.sh
Corresponding PR from this: https://github.com/iter8-tools/iter8-controller/pull/166
> use simpler image tag

- iter8_analytics/api/analytics/successcriteria.py
- tests/metrics_backend/successcriteria_tests.py
> enriching conclusion str

- iter8_analytics/api/analytics/successcriteria.py
- tests/metrics_backend/successcriteria_tests.py
> Enriching conclusion str for v0.2

- Dockerfile
- Resolves #119 
- Tested as a docker container and a Kubernetes service with Prometheus
> Changes for dockerizing iter8 analytics v1.0.0

- iter8_analytics/api/analytics/experiment.py
- iter8_analytics/api/analytics/types.py
This uses the utilities to provide a better assessment of the winner.
> Assess winner better

- iter8_analytics/api/analytics/experiment.py
- tests/api/analytics/endpoints/experiment_test.py
1. Nicer error message when counter metric is used as reward
2. Nicer error message when more than one metric is used as reward
> validate reward metric

- .travis.yml
- iter8_analytics/api/analytics/detailedcriterion.py
- iter8_analytics/api/analytics/detailedmetric.py
- iter8_analytics/api/analytics/detailedversion.py
- iter8_analytics/api/analytics/experiment.py
- iter8_analytics/api/analytics/types.py
- tests/api/analytics/endpoints/experiment_test.py
- tests/e2e/e2e-test.sh
- tests/fastapi_app_test.py
1. Ratio Statistics are now (partially) populated. Specifically credible intervals are populated
2. e2e tests are re-enabled.
> credible interval, e2e tests

- iter8_analytics/api/analytics/endpoints/examples.py
- iter8_analytics/api/analytics/experiment.py
- iter8_analytics/api/analytics/types.py
- tests/api/analytics/endpoints/experiment_test.py
No new functionality in this PR. However, this fixes the bug pointed out by @kalantar (when start_time of the experiment equals the current_time).
> Fix the bug caused by start_time = current_time

- iter8_analytics/api/analytics/detailedcriterion.py
- iter8_analytics/api/analytics/experiment.py
- requirements.txt
- tests/api/analytics/endpoints/experiment_test.py
Relative thresholds functionality is now implemented.
Can be tested using the swagger UI and also covered with unit tests.
> Relative threshold 

- iter8_analytics/api/analytics/detailedcriterion.py
- iter8_analytics/api/analytics/experiment.py
- iter8_analytics/api/analytics/types.py
- tests/api/analytics/endpoints/experiment_test.py
Threshold assessments are now populated
This also affects the way criteria are checked.
> Threshold assessments

- iter8_analytics/api/analytics/experiment.py
- tests/api/analytics/endpoints/experiment_test.py
This PR enables the `max increment` feature within `traffic control` field of the CR.
> max increment

- iter8_analytics/api/analytics/detailedcriterion.py
- iter8_analytics/api/analytics/endpoints/examples.py
- tests/api/analytics/endpoints/experiment_test.py
> relative bug

- install/kubernetes/helm/iter8-analytics/templates/deployment.yaml
Last PR updated iter8-analytics.yaml directly. Should have updated the helm template file too.
> update deployment yaml too

- iter8_analytics/api/v2/metrics.py
Error messages now explicitly mention version name and metric name
> Fixed error handling 

- iter8_analytics/tests/unit/v2/data/inputs/inputs.py
- iter8_analytics/tests/unit/v2/data/prom_responses/prometheus_sample_no_response.json
- iter8_analytics/tests/unit/v2/experiment_v2_test.py
The remaining coverage from this file are for the A/B/n and performance strategies. They will be covered at a later time.
> increased test coverage for v2 exp.py

- iter8_analytics/api/v2/metrics.py
- iter8_analytics/tests/unit/v2/experiment_v2_test.py
- Bug fixed in extrapolate function
- test case added
> extrapolate function bug fixed

- iter8_analytics/api/v2/examples/examples_ab.py
- iter8_analytics/api/v2/examples/examples_abn.py
- iter8_analytics/api/v2/examples/examples_canary.py
- iter8_analytics/api/v2/metrics.py
- iter8_analytics/tests/integration/data/inputs/metrics1.json
- iter8_analytics/tests/integration/data/inputs/metrics2.json
- iter8_analytics/tests/integration/data/inputs/metrics3.json
- iter8_analytics/tests/integration/data/inputs/metrics4.json
- iter8_analytics/tests/integration/data/inputs/metrics5.json
> interval changed to elapsedTime

- README.md
> Updated readme for locally running and testing iter8-analytics service

- iter8_analytics/api/v2/examples/examples_ab.py
- iter8_analytics/api/v2/examples/examples_abn.py
- iter8_analytics/api/v2/examples/examples_canary.py
- iter8_analytics/api/v2/metrics.py
- iter8_analytics/tests/integration/data/inputs/metrics1.json
- iter8_analytics/tests/integration/data/inputs/metrics2.json
- iter8_analytics/tests/integration/data/inputs/metrics3.json
- iter8_analytics/tests/integration/data/inputs/metrics4.json
- iter8_analytics/tests/integration/data/inputs/metrics5.json
- iter8_analytics/tests/unit/v2/experiment_test.py
- iter8_analytics/tests/unit/v2/metrics_test.py
> Fix elapsedTime stringification so that it works for all metric APIs and not just Prometheus

- .github/workflows/multi-db-integration-test.yaml
- .github/workflows/python-app.yaml
- iter8_analytics/api/utils.py
- iter8_analytics/api/v2/examples/examples_ab.py
- iter8_analytics/api/v2/examples/examples_abn.py
- iter8_analytics/api/v2/examples/examples_canary.py
- iter8_analytics/api/v2/examples/examples_metrics.py
- iter8_analytics/api/v2/experiment.py
- iter8_analytics/api/v2/metrics.py
- iter8_analytics/api/v2/types.py
- iter8_analytics/tests/unit/v2/experiment_test.py
- iter8_analytics/tests/unit/v2/metrics_test.py
Resolves #262 
Introduces  listing using .pylintrc configuration.
> Enable authentication during metric DB queries

- iter8_analytics/api/v2/metrics.py
> timeout increased to 5 seconds

- iter8_analytics/api/v2/examples/examples_ab.py
- iter8_analytics/api/v2/examples/examples_abn.py
- iter8_analytics/api/v2/examples/examples_canary.py
- iter8_analytics/api/v2/metrics.py
- iter8_analytics/tests/unit/v2/experiment_test.py
- iter8_analytics/tests/unit/v2/metrics_test.py
Resolves #272 
Added test cases for the same
> Analytics now uses previous state if metrics not available

- CONTRIBUTING.md
- README.md
This PR partially addresses issue iter8-tools/iter8#687
> Contributing and readme changes

- iter8_analytics/api/v2/experiment.py
- iter8_analytics/api/v2/metrics.py
- iter8_analytics/api/v2/types.py
- iter8_analytics/tests/unit/v2/data/experiments/metricscollected.json
- iter8_analytics/tests/unit/v2/metrics_test.py
- requirements.txt
- test-requirements.txt
Signed-off-by: Srinivasan Parthasarathy <5309125+sriumcp@users.noreply.github.com>
This PR partly addresses iter8-tools/iter8#684
> Support for Iter8 built in metrics

- iter8_analytics/api/v2/experiment.py
- iter8_analytics/tests/unit/v2/experiment_test.py
Signed-off-by: Srinivasan Parthasarathy <spartha@us.ibm.com>
Fixes iter8-tools/iter8#785
> experiment without objectives should work

- iter8_analytics/api/v2/examples/examples_canary.py
- iter8_analytics/api/v2/examples/examples_metrics.py
- iter8_analytics/api/v2/metrics.py
- iter8_analytics/api/v2/types.py
- iter8_analytics/tests/unit/v2/experiment_test.py
Partially addresses iter8-tools/iter8#742
> Mocking metrics

- iter8_analytics/api/v2/experiment.py
- iter8_analytics/tests/unit/v2/experiment_test.py
- iter8_analytics/tests/unit/v2/metrics_test.py
Signed-off-by: Srinivasan Parthasarathy <spartha@us.ibm.com>
Fixes iter8-tools/iter8#791
> bug fix for computing feasible versions

- iter8_analytics/api/v2/metrics.py
- iter8_analytics/tests/unit/v2/experiment_test.py
Signed-off-by: Srinivasan Parthasarathy <spartha@us.ibm.com>
Fixes iter8-tools/iter8#795
> fixed negative time delta bug

- .github/workflows/python-app.yaml
- iter8_analytics/api/v2/metrics.py
Disables certificate verification for https requests.
> disable certificate verification

- .github/workflows/python-app.yaml
Fixes the pylint issue by *not* linting test files.
Signed-off-by: Srinivasan Parthasarathy <spartha@us.ibm.com>
> Ignore test files while linting
